### ISSUE TITLE
'resulting_size' in authorize() method

### ISSUE THREAD

**Issue by wakitosh** [cantaloupe-project/cantaloupe#298]
I am working on updating Cantaloupe 4.0.3 to 4.1.2. The following is described in the authorize() method of delegates.rb: There is no problem with this writing in 4.0.3, but it is an error in 4.1.2. Where is the problem?

    resulting_size = context['resulting_size']
    return true if ((resulting_size['width'] <= 360) && (resulting_size['height'] <= 360))

The error message is as follows.

500 Internal Server Error
javax.script.ScriptException: java.lang.NoSuchMethodException: (NoMethodError) undefined method `[] 'for nil: NilClass

I'm a newbie to Ruby, so I might be writing it strangely.

**Comment by adolski** [comment]
Hi @wakitosh ,

Thanks for reporting this bug. I'll push a fix soon that will be incorporated into 4.1.3.

**Comment by wakitosh** [comment]
Thank you, @adolski 
Cantaloupe is a very good product, but unfortunately I don't think there is a lot of adoption cases in Japan. I would like to spread cantaloupe in Japan.

**Comment by adolski** [comment]
Thanks @wakitosh, glad you are enjoying it.
